## NUMPY

Numpy is a library for Scientific Computing in Python.It provides support for arrays and matrices and mathematical function to operate on these data structures.

# 📘 NumPy Complete Cheat Sheet

## 🔹 1. Array Creation

```python
np.array()
np.zeros()
np.ones()
np.empty()
np.full()
np.arange()
np.linspace()
np.eye()
np.identity()
np.random.random()
np.random.randint()
```

---

## 🔹 2. Array Attributes

```python
arr.shape
arr.ndim
arr.size
arr.dtype
arr.itemsize
```

---

## 🔹 3. Reshaping & Flattening

```python
arr.reshape()
arr.flatten()
arr.ravel()
arr.T
np.transpose()
```

---

## 🔹 4. Indexing & Slicing

```python
arr[i]
arr[i:j]
arr[:, i]
arr[i, j]
arr[::2]
```

---

## 🔹 5. Joining & Splitting

```python
np.concatenate()
np.vstack()
np.hstack()
np.split()
np.array_split()
```

---

## 🔹 6. Adding / Removing Elements

```python
np.append()
np.insert()
np.delete()
```

---

## 🔹 7. Mathematical Operations

```python
np.add()
np.subtract()
np.multiply()
np.divide()
np.power()
np.sqrt()
np.abs()
```

---

## 🔹 8. Statistical Functions

```python
np.mean()
np.median()
np.std()
np.var()
np.min()
np.max()
np.sum()
np.prod()
```

---

## 🔹 9. Sorting & Searching

```python
np.sort()
np.argsort()
np.where()
np.searchsorted()
```

---

## 🔹 10. Linear Algebra

```python
np.dot()
np.matmul()
np.linalg.inv()
np.linalg.det()
np.linalg.eig()
```

---

## 🔹 11. Logical Operations

```python
np.logical_and()
np.logical_or()
np.logical_not()
np.all()
np.any()
```

---

## 🔹 12. Set Operations

```python
np.unique()
np.intersect1d()
np.union1d()
np.setdiff1d()
```

---

## 🔹 13. Random Module

```python
np.random.rand()
np.random.randn()
np.random.randint()
np.random.choice()
np.random.seed()
```

---

## 🔹 14. File Handling

```python
np.save()
np.load()
np.savetxt()
np.loadtxt()
```

---

## 🔹 15. Data Type Handling

```python
arr.astype()
np.int32
np.float64
np.bool_
```

---

## 🔹 16. Special Functions

```python
np.clip()
np.round()
np.floor()
np.ceil()
np.exp()
np.log()
```

---

## 🔹 17. Broadcasting

```python
# automatic shape matching
```

---

## 🔹 18. Useful Tricks

```python
arr.tolist()
arr.flags.writeable = False
np.set_printoptions()
```

---

## 🚀 Summary

* NumPy = Fast numerical computation
* Arrays = fixed size
* Vectorized operations = no loops needed

---

💡 Tip: Practice each function with small examples to master NumPy.


In [5]:
from traceback import print_tb

## Importing Numpy
import numpy as np

In [6]:
## Creating Arrays
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(5,)

In [9]:
arr1=np.array([1,2,3,4,5])
arr2=arr1.reshape(1,5)
print(arr2)


[[1 2 3 4 5]]


In [10]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr2.shape

(2, 5)

In [11]:
arr3=np.arange(1,20,3)
print(arr3)

[ 1  4  7 10 13 16 19]


In [12]:
x=np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
y=np.eye(3)
print(y)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
arr=np.array([[1,2,3],[4,5,6]])
print(f'Array: {arr}')
print(f'Shape: {arr.shape}')
print(f'Dimension: {arr.ndim}')
print(f'Size: {arr.size}')
print(arr.dtype)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Size: 6
int64


In [15]:
### Numpy Vectorized Operation
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print(f'Addition: {arr1+arr2}')
print(f'Subtraction: {arr1-arr2}')
print(f'Multiplication: {arr1*arr2}')
print(f'Division: {arr1/arr2}')

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [16]:
##Universal Function
print(f'Square Root{np.sqrt(arr2)}')
print(f'Exponet{np.exp(arr2)}')
print(f'Sine: {np.sin(arr2)}')
print(f'log: {np.log(arr2)}')

Square Root[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
Exponet[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
Sine: [-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
log: [2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]


In [17]:
##Slicing and Indexing
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(f'Array: {arr}')

Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [18]:
arr[0,0]

np.int64(1)

In [19]:

arr[1:,1:]

array([[ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [20]:
## Statistical Operation
arr1=np.array([1,2,3,4,5])
mean=np.mean(arr1)
print(mean)
std_dev=np.std(arr)
print(std_dev)
variance=np.var(arr1)
print(variance)
normal=(arr1-mean)/std_dev
print(normal)

3.0
4.320493798938574
2.0
[-0.46291005 -0.23145502  0.          0.23145502  0.46291005]


1. Write a Python program to convert a list of numeric value into a one-dimensional

NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional numpy array: [ 12.23 13.32 100. 36.32]

In [21]:
ls=[12.23, 13.32, 100, 36.32]
arr=np.array(ls)
print(arr)

[ 12.23  13.32 100.    36.32]


2. Create a 3x3 matrix with values ranging from 2 to 10.
Expected Output:
[[ 2 3 4]
[ 5 6 7]
[ 8 9 10]]

In [22]:
print(np.arange(2,11).reshape(3,3))

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a Python program to create a null vector of size 10 and update sixth value to 11.
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [23]:
null_Vector=np.zeros(10,)
print(null_Vector)
null_Vector[5]=11
print(null_Vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


4. Write a Python program to reverse an array (first element becomes last).
Original array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]
Reverse array:
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [24]:
arr=np.arange(12,38)
print(arr)
print(arr[::-1])

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]
[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [25]:
I_one=np.ones((5,5))
print(I_one)
print('<-------------------------------------------------------------------------------------------------------->')
I_one[1:4,1:4]=0
print(I_one)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
<-------------------------------------------------------------------------------------------------------->
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [26]:
I_one_2=np.ones((4,4))
print(I_one_2)
print('<------------------------------------------------------------------------------------------------------>')
pad=np.pad(I_one_2,pad_width=1,mode='constant',constant_values=0)
print(pad)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<------------------------------------------------------------------------------------------------------>
[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
a=np.zeros((8,8))
print(a)
print('<-------------------------------------------------------------------------------------------------------->')
a[::2,1::2]=1
a[1::2,::2]=1
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
<-------------------------------------------------------------------------------------------------------->
[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [28]:
##Coverting List and Tuples to the array
a=[1,2,3,4,5,6,7,8]
print(np.array(a))
b=((1,2,3),(4,5,6))
print(np.array(b))

[1 2 3 4 5 6 7 8]
[[1 2 3]
 [4 5 6]]


In [29]:
## apending values
a=np.append(a,5)
print(a)

[1 2 3 4 5 6 7 8 5]


In [30]:
arr=np.array([ 1.00000000+0.j,0.70710678+0.70710678j])
print(arr.real)
print(arr.imag)

[1.         0.70710678]
[0.         0.70710678]


In [31]:
print(a.size)
print(a.itemsize)
print(a.itemsize*a.size)

9
8
72


In [32]:
Array1=np.array([0,10,40,60])
Array2=np.array([10,30,40])

print(np.intersect1d(Array1,Array2))

[10 40]


In [33]:
a=np.array([1,2])
b=np.array([5,0])
print(a>b)
print(a<b)


[False  True]
[ True False]


In [34]:
x=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(x.flatten())



[ 1  2  3  4  5  6  7  8  9 10]


In [35]:
c=x.astype(str)
print(c)


[['1' '2' '3' '4' '5']
 ['6' '7' '8' '9' '10']]


In [36]:
print(np.tri(3,3,-1))

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]


In [37]:
print(np.tri(3,3,0))

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [38]:
print(np.tri(3,3,1))

[[1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [39]:
a=np.array([[0, 1, 3], [5, 7, 9]])
b=np.array([[12,56,0],[1,1,1]])
print(np.concatenate((a,b),axis=0))

[[ 0  1  3]
 [ 5  7  9]
 [12 56  0]
 [ 1  1  1]]


In [40]:
a.flags.writeable=False
print(a)

[[0 1 3]
 [5 7 9]]


In [42]:
array=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

print(array*3)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [44]:
print(array.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [45]:
array=np.random.random(10)
print(array)

[0.02776094 0.30662777 0.7243759  0.02593247 0.43507991 0.42641274
 0.90642698 0.78508482 0.99322114 0.69720652]


In [46]:
import numpy as np

# create random array
arr = np.random.random(10)

print("Original array elements:")
print(arr)

# set precision to 3
np.set_printoptions(precision=3)

print("\nPrint array values with precision 3:")
print(arr)

# convert to list
lst = arr.tolist()

print("\nConverted Python list:")
print(lst)

Original array elements:
[0.42660146 0.81985375 0.91021968 0.50426913 0.3488517  0.23223481
 0.88078696 0.68396363 0.2190531  0.18645271]

Print array values with precision 3:
[0.427 0.82  0.91  0.504 0.349 0.232 0.881 0.684 0.219 0.186]

Converted Python list:
[0.4266014611864787, 0.8198537493223452, 0.9102196806821339, 0.504269133901696, 0.34885169881837974, 0.23223480547664366, 0.8807869554253417, 0.6839636307280398, 0.21905309640502257, 0.18645271025461174]


In [47]:



arr = np.array([1.6e-10, 1.6, 1200, 0.235])

print("Original array elements:")
print(arr)

# suppress scientific notation + set precision
np.set_printoptions(suppress=True, precision=3)

print("\nPrint array values with precision 3:")
print(arr)

Original array elements:
[1.60e-10 1.60e+00 1.20e+03 2.35e-01]

Print array values with precision 3:
[   0.       1.6   1200.       0.235]


In [50]:
array=np.array(
    [[10,20,30],
     [40,50,60],
     [70,80,90]]
)

new_col=[[5],[6],[7]]
print(np.hstack((array,new_col)))

[[10 20 30  5]
 [40 50 60  6]
 [70 80 90  7]]


In [51]:
array=np.array([10,20,30,40,50,60,70,80,90,100])
array=np.delete(array,[0,3,4])
print(array)

[ 20  30  60  70  80  90 100]
